### PR TITLE
fix install conflict due to torchvision 0.18.1

### PR DESCRIPTION
**Pull request by dhuangnm**
Limit torchvision version to <=0.18.0 in requirements-test.txt.

### CODE REVIEW

**Review by derekk-nm — APPROVED** [review]

**Comment by mgoin** [comment]
Is this an upstream issue as well?

**Review by dbarbuzzi — APPROVED** [review]

**Comment by dhuangnm** [comment]
> Is this an upstream issue as well?

It looks upstream has fixed it in this PR: https://github.com/vllm-project/vllm/pull/5772

**Review by andy-neuma — APPROVED** [review]
thanks

**Comment by dhuangnm** [comment]
Maybe we can just wait for the fix in next upstream sync? @mgoin @robertgshaw2-neuralmagic 

It's not blocking testing now and jobs don't fail due to the error.

**Comment by dhuangnm** [comment]
Fixed in upstream, no changes needed here.

**Pull request closed without merging**
